name: ci-tests
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: |
          cd api
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
          python3 -m unittest discover
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AQI_IP }}
          username: 'ec2-user'
          key: ${{ secrets.EC2_SSH_KEY_AQI }}
          port: '22'
          script: |
            whoami
            pwd
            cd air-quality-app
            git pull
            cd my-app
            sudo cp -r  build/* /usr/share/nginx/html/
            sudo systemctl restart nginx
            cd ..
            cd api
            PID=$(lsof -t -i :5000)
            kill $PID
            python3 main.py &
            echo "Done"
            


